spring.application.name=test

##local
spring.datasource.url=jdbc:mariadb://localhost:3306/kjh
spring.datasource.username=root
spring.datasource.password=brain192

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# JDBC
spring.sql.init.mode=always

# -parameters
spring.main.allow-bean-definition-overriding=true

file.upload-dir=uploads

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG